In [1]:
import pandas as pd
import pickle
from sklearn.model_selection import GridSearchCV, TimeSeriesSplit
from sklearn.metrics import make_scorer
import xgboost as xgb

from Training_Pipeline import calc_lift

In [2]:
xgb

In [3]:
grouped_data = pd.read_csv('TestChurnComplete/original.csv',index_col=[0,1])
grouped_data

y = grouped_data['is_churn'].astype(int)

X = grouped_data.drop(['is_churn'],axis=1)

#churn rate
X

,,like_per_month,newfriend_per_month,post_per_month,adview_per_month,dislike_per_month,unfriend_per_month,message_per_month,reply_per_month,account_tenure,adview_per_post,reply_per_message,like_per_post,post_per_message,unfriend_per_newfriend,dislike_pcnt,unfriend_per_newfriend_scaled,newfriend_pcnt_chng,days_since_newfriend,unfriend_28day_avg_84day_obs,unfriend_28day_avg_84day_obs_scaled
account_id,observation_date,,,,,,,,,,,,,,,,,,,,
27,2020-03-01,28.0,5.0,14.0,33.0,2.0,1.0,1.0,0.0,55.0,2.357143,0.000000,2.000000,14.000000,0.20,0.066667,0.101818,4.000000,3.0,0.333333,0.509091
51,2020-03-01,26.0,5.0,4.0,19.0,4.0,1.0,42.0,28.0,55.0,4.750000,0.666667,6.500000,0.095238,0.20,0.133333,0.203636,-0.166667,1.0,0.666667,1.018182
95,2020-03-01,74.0,5.0,64.0,17.0,20.0,0.0,12.0,6.0,55.0,0.265625,0.500000,1.156250,5.333334,0.00,0.212766,0.000000,0.250000,1.0,0.000000,0.000000
123,2020-03-01,28.0,6.0,13.0,4.0,25.0,0.0,11.0,1.0,55.0,0.307692,0.090909,2.153846,1.181818,0.00,0.471698,0.000000,1.000000,2.0,0.000000,0.000000
189,2020-03-01,3.0,1.0,8.0,16.0,2.0,0.0,0.0,0.0,55.0,2.000000,0.000000,0.375000,0.000000,0.00,0.400000,0.000000,0.000000,15.0,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13132,2020-05-10,19.0,0.0,20.0,2.0,3.0,0.0,27.0,6.0,25.0,0.100000,0.222222,0.950000,0.740741,0.00,0.136364,0.000000,0.000000,0.0,0.000000,0.000000
13141,2020-05-10,3.0,1.0,6.0,9.0,1.0,0.0,13.0,5.0,25.0,1.500000,0.384615,0.500000,0.461538,0.00,0.250000,0.000000,0.000000,18.0,0.000000,0.000000
13155,2020-05-10,2.0,0.0,1.0,1.0,1.0,0.0,27.0,17.0,25.0,1.000000,0.629630,2.000000,0.037037,0.00,0.333333,0.000000,0.000000,0.0,0.000000,0.000000
13171,2020-05-10,15.0,6.0,44.0,16.0,1.0,0.0,26.0,6.0,25.0,0.363636,0.230769,0.340909,1.692308,0.00,0.062500,0.000000,0.000000,6.0,0.000000,0.000000
13248,2020-05-10,439.0,50.0,276.0,664.0,44.0,1.0,448.0,50.0,25.0,2.405797,0.111607,1.590580,0.616071,0.02,0.091097,0.022400,0.000000,0.0,0.333333,1.120000

In [4]:
tscv = TimeSeriesSplit(
    n_splits=2)

In [5]:
score_models = {
    'lift':make_scorer(calc_lift, response_method='predict_proba'),
    'AUC':'roc_auc'
}

In [6]:
xgb_model = xgb.XGBClassifier(objective='binary:logistic')
xgb_model

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=None,
              n_jobs=None, num_parallel_tree=None, ...)

In [7]:
test_params = {
    'max_depth':[1,2,4,6],
    'learning_rate':[0.1,0.2,0.3,0.4],
    'n_estimators':[20,40,80,120],
    'min_child_weight':[3,6,9,12]
}
test_params

{'max_depth': [1, 2, 4, 6],
 'learning_rate': [0.1, 0.2, 0.3, 0.4],
 'n_estimators': [20, 40, 80, 120],
 'min_child_weight': [3, 6, 9, 12]}

In [8]:
#refit es con toda la informacion

gsearch = GridSearchCV(
    estimator=xgb_model, 
    n_jobs=-1,
    scoring=score_models,
    cv=tscv,
    verbose=1,
    return_train_score=False,
    param_grid=test_params,
    refit='AUC'
)

gsearch

GridSearchCV(cv=TimeSeriesSplit(gap=0, max_train_size=None, n_splits=2, test_size=None),
             estimator=XGBClassifier(base_score=None, booster=None,
                                     callbacks=None, colsample_bylevel=None,
                                     colsample_bynode=None,
                                     colsample_bytree=None, device=None,
                                     early_stopping_rounds=None,
                                     enable_categorical=False, eval_metric=None,
                                     feature_types=None, feature_weights=None,
                                     gamma=Non...
                                     missing=nan, monotone_constraints=None,
                                     multi_strategy=None, n_estimators=None,
                                     n_jobs=None, num_parallel_tree=None, ...),
             n_jobs=-1,
             param_grid={'learning_rate': [0.1, 0.2, 0.3, 0.4],
                         'max_depth': [1, 2, 4, 6],
                         'min_child_weight': [3, 6, 9, 12],
                         'n_estimators': [20, 40, 80, 120]},
             refit='AUC',
             scoring={'AUC': 'roc_auc',
                      'lift': make_scorer(calc_lift, response_method='predict_proba')},
             verbose=1)

In [9]:
gsearch.fit(X,y)

Fitting 2 folds for each of 256 candidates, totalling 512 fits

GridSearchCV(cv=TimeSeriesSplit(gap=0, max_train_size=None, n_splits=2, test_size=None),
             estimator=XGBClassifier(base_score=None, booster=None,
                                     callbacks=None, colsample_bylevel=None,
                                     colsample_bynode=None,
                                     colsample_bytree=None, device=None,
                                     early_stopping_rounds=None,
                                     enable_categorical=False, eval_metric=None,
                                     feature_types=None, feature_weights=None,
                                     gamma=Non...
                                     missing=nan, monotone_constraints=None,
                                     multi_strategy=None, n_estimators=None,
                                     n_jobs=None, num_parallel_tree=None, ...),
             n_jobs=-1,
             param_grid={'learning_rate': [0.1, 0.2, 0.3, 0.4],
                         'max_depth': [1, 2, 4, 6],
                         'min_child_weight': [3, 6, 9, 12],
                         'n_estimators': [20, 40, 80, 120]},
             refit='AUC',
             scoring={'AUC': 'roc_auc',
                      'lift': make_scorer(calc_lift, response_method='predict_proba')},
             verbose=1)

In [10]:
df = pd.DataFrame(gsearch.cv_results_)
df.sort_values(by='mean_test_AUC', ascending=False, inplace=True)

In [11]:
df

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_learning_rate,param_max_depth,param_min_child_weight,param_n_estimators,params,split0_test_lift,split1_test_lift,mean_test_lift,std_test_lift,rank_test_lift,split0_test_AUC,split1_test_AUC,mean_test_AUC,std_test_AUC,rank_test_AUC
199,0.072871,0.020963,0.019811,0.001892,0.4,1,6,120,"{'learning_rate': 0.4, 'max_depth': 1, 'min_ch...",3.458251,3.847048,3.652650,0.194399,72,0.713745,0.725503,0.719624,0.005879,1
195,0.074125,0.017736,0.018174,0.000167,0.4,1,3,120,"{'learning_rate': 0.4, 'max_depth': 1, 'min_ch...",3.351843,3.770107,3.560975,0.209132,121,0.710526,0.727320,0.718923,0.008397,2
31,0.087890,0.024354,0.019023,0.000710,0.1,2,12,120,"{'learning_rate': 0.1, 'max_depth': 2, 'min_ch...",3.671066,4.077871,3.874469,0.203402,1,0.712320,0.724778,0.718549,0.006229,3
203,0.073248,0.020860,0.017635,0.000512,0.4,1,9,120,"{'learning_rate': 0.4, 'max_depth': 1, 'min_ch...",3.458251,3.847048,3.652650,0.194399,72,0.714314,0.722764,0.718539,0.004225,4
206,0.058424,0.017609,0.021867,0.001410,0.4,1,12,80,"{'learning_rate': 0.4, 'max_depth': 1, 'min_ch...",3.511455,3.923989,3.717722,0.206267,45,0.716278,0.720411,0.718345,0.002066,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
255,0.146871,0.035688,0.023236,0.000629,0.4,6,12,120,"{'learning_rate': 0.4, 'max_depth': 6, 'min_ch...",2.660193,3.077639,2.868916,0.208723,249,0.648477,0.649565,0.649021,0.000544,252
241,0.098716,0.014315,0.025233,0.002925,0.4,6,3,40,"{'learning_rate': 0.4, 'max_depth': 6, 'min_ch...",2.873008,3.000698,2.936853,0.063845,244,0.630804,0.661251,0.646027,0.015223,253
243,0.224241,0.055278,0.033710,0.005023,0.4,6,3,120,"{'learning_rate': 0.4, 'max_depth': 6, 'min_ch...",2.500581,2.846816,2.673699,0.173117,256,0.635629,0.653808,0.644719,0.009089,254
246,0.139800,0.039229,0.036241,0.008679,0.4,6,6,80,"{'learning_rate': 0.4, 'max_depth': 6, 'min_ch...",2.660193,2.846816,2.753504,0.093311,255,0.644620,0.639146,0.641883,0.002737,255
247,0.222867,0.055401,0.029774,0.000828,0.4,6,6,120,"{'learning_rate': 0.4, 'max_depth': 6, 'min_ch...",2.713397,2.923757,2.818577,0.105180,251,0.645376,0.629918,0.637647,0.007729,256

In [12]:
df.to_csv('crossval_xgb.csv', index=False)

In [13]:
gsearch.best_estimator_

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.4, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=1,
              max_leaves=None, min_child_weight=6, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=120,
              n_jobs=None, num_parallel_tree=None, ...)

In [14]:
with open('xgb_model.pkl', 'wb') as fid:
    pickle.dump(gsearch.best_estimator_, fid)

In [15]:
0.712850

0.71285

In [16]:
0.714576

0.714576