In [1]:
%load_ext sql
%sql postgresql://postgres:postgres@localhost/churn

Connecting to 'postgresql://postgres:***@localhost/churn'

In [2]:
%sql set search_path to socialnet7;

Running query in 'postgresql://postgres:***@localhost/churn'

++
||
++
++

RATIO METRIC

In [3]:
%%sql
SET
  SEARCH_PATH TO SOCIALNET7;

WITH
  NUM_METRIC AS (
    SELECT
      ACCOUNT_ID,
      METRIC_TIME,
      METRIC_VALUE AS NUM_VALUE
    FROM
      METRIC M
      INNER JOIN METRIC_NAME N ON M.METRIC_NAME_ID = N.METRIC_NAME_ID
      AND N.METRIC_NAME = 'adview_per_month'
      AND M.METRIC_TIME BETWEEN '2020-03-01' AND '2020-05-10'
    ORDER BY
      METRIC_TIME
  ),
  DEN_METRIC AS (
    SELECT
      ACCOUNT_ID,
      METRIC_TIME,
      METRIC_VALUE AS DEN_VALUE
    FROM
      METRIC M
      INNER JOIN METRIC_NAME N ON M.METRIC_NAME_ID = N.METRIC_NAME_ID
      AND N.METRIC_NAME = 'post_per_month'
      AND M.METRIC_TIME BETWEEN '2020-03-01' AND '2020-05-10'
    ORDER BY
      METRIC_TIME
  )
SELECT
  D.ACCOUNT_ID,
  D.METRIC_TIME,
  NUM_VALUE,
  DEN_VALUE,
  CASE
    WHEN DEN_VALUE > 0 THEN COALESCE(NUM_VALUE, 0.0) / DEN_VALUE
    ELSE 0
  END AS METRIC_VALUE
FROM
  DEN_METRIC D
  LEFT OUTER JOIN NUM_METRIC N ON N.ACCOUNT_ID = D.ACCOUNT_ID
  AND N.METRIC_TIME = D.METRIC_TIME

Running query in 'postgresql://postgres:***@localhost/churn'

124825 rows affected.

+------------+---------------------+-----------+-----------+--------------+
| account_id |     metric_time     | num_value | den_value | metric_value |
+------------+---------------------+-----------+-----------+--------------+
|    1712    | 2020-03-01 00:00:00 |    15.0   |    45.0   |  0.33333334  |
|    3297    | 2020-03-01 00:00:00 |    3.0    |    21.0   |  0.14285715  |
|    4947    | 2020-03-01 00:00:00 |    35.0   |    27.0   |  1.2962962   |
|    5523    | 2020-03-01 00:00:00 |    25.0   |    48.0   |  0.5208333   |
|    3296    | 2020-03-01 00:00:00 |    5.0    |    1.0    |     5.0      |
|    3295    | 2020-03-01 00:00:00 |    99.0   |    91.0   |  1.0879121   |
|    4946    | 2020-03-01 00:00:00 |    16.0   |    10.0   |     1.6      |
|    1111    | 2020-03-01 00:00:00 |    19.0   |    13.0   |  1.4615384   |
|    368     | 2020-03-01 00:00:00 |    29.0   |    19.0   |  1.5263158   |
|    3294    | 2020-03-01 00:00:00 |    18.0   |    19.0   |  0.94736844  |
+------------+---------------------+-----------+-----------+--------------+
Truncated to displaylimit of 10.

TOTAL METRIC

In [4]:
%%sql 
SET
  SEARCH_PATH TO SOCIALNET7;

SELECT
  ACCOUNT_ID,
  METRIC_TIME,
  --STRING_AGG(METRIC_VALUE::TEXT, '+') AS METRIC_SUM,
  15,
  SUM(METRIC_VALUE) AS METRIC_TOTAL
FROM
  METRIC M
  INNER JOIN METRIC_NAME N ON M.METRIC_NAME_ID = N.METRIC_NAME_ID
  AND METRIC_NAME IN ('like_per_month', 'dislike_per_month')
WHERE
  METRIC_TIME BETWEEN '2020-03-01' AND '2020-04-01'
GROUP BY
  ACCOUNT_ID,
  METRIC_TIME

Running query in 'postgresql://postgres:***@localhost/churn'

55483 rows affected.

+------------+---------------------+----------+--------------+
| account_id |     metric_time     | ?column? | metric_total |
+------------+---------------------+----------+--------------+
|    7914    | 2020-03-29 00:00:00 |    15    |    118.0     |
|    2417    | 2020-03-01 00:00:00 |    15    |    105.0     |
|    4080    | 2020-03-01 00:00:00 |    15    |     47.0     |
|   10169    | 2020-03-15 00:00:00 |    15    |     96.0     |
|    5760    | 2020-03-22 00:00:00 |    15    |     16.0     |
|   10283    | 2020-03-01 00:00:00 |    15    |     7.0      |
|    1034    | 2020-03-01 00:00:00 |    15    |    181.0     |
|   11587    | 2020-03-15 00:00:00 |    15    |     3.0      |
|    1621    | 2020-03-01 00:00:00 |    15    |    201.0     |
|    5985    | 2020-03-08 00:00:00 |    15    |     1.0      |
+------------+---------------------+----------+--------------+
Truncated to displaylimit of 10.

percentage change

In [5]:
%%sql
SET
	SEARCH_PATH TO SOCIALNET7;

WITH
	END_METRIC AS (
		SELECT
			ACCOUNT_ID,
			METRIC_TIME,
			METRIC_VALUE AS END_VALUE
		FROM
			METRIC M
			INNER JOIN METRIC_NAME N ON M.METRIC_NAME_ID = N.METRIC_NAME_ID
			AND N.METRIC_NAME = 'newfriend_per_month'
			AND METRIC_TIME BETWEEN '2020-04-01' AND '2020-05-10'
	),
	START_METRIC AS (
		SELECT
			ACCOUNT_ID,
			METRIC_TIME,
			METRIC_VALUE AS START_VALUE
		FROM
			METRIC M
			INNER JOIN METRIC_NAME N ON M.METRIC_NAME_ID = N.METRIC_NAME_ID
			AND N.METRIC_NAME = 'newfriend_per_month'
			AND METRIC_TIME BETWEEN '2020-04-01'::TIMESTAMP - INTERVAL '4 week' AND '2020-05-10'::TIMESTAMP - INTERVAL '4 week'
		ORDER BY
			METRIC_TIME
	)
SELECT
	S.ACCOUNT_ID,
	S.METRIC_TIME + INTERVAL '4 week' AS END_TIME,
	START_VALUE,
	END_VALUE,
	(COALESCE(END_VALUE, 0.0) / START_VALUE) - 1.0 AS PERCENT_CHANGE_PER_MONTH
FROM
	START_METRIC S
	LEFT OUTER JOIN END_METRIC E ON S.ACCOUNT_ID = E.ACCOUNT_ID
	AND E.METRIC_TIME = (S.METRIC_TIME + INTERVAL '4 week')
WHERE
	START_VALUE > 0

Running query in 'postgresql://postgres:***@localhost/churn'

59663 rows affected.

+------------+---------------------+-------------+-----------+--------------------------+
| account_id |       end_time      | start_value | end_value | percent_change_per_month |
+------------+---------------------+-------------+-----------+--------------------------+
|     0      | 2020-04-05 00:00:00 |     3.0     |    2.0    |   -0.3333333134651184    |
|     0      | 2020-04-12 00:00:00 |     3.0     |    2.0    |   -0.3333333134651184    |
|     0      | 2020-04-19 00:00:00 |     1.0     |    5.0    |           4.0            |
|     0      | 2020-04-26 00:00:00 |     2.0     |    4.0    |           1.0            |
|     0      | 2020-05-03 00:00:00 |     2.0     |    5.0    |           1.5            |
|     0      | 2020-05-10 00:00:00 |     2.0     |    5.0    |           1.5            |
|     1      | 2020-04-05 00:00:00 |     3.0     |    2.0    |   -0.3333333134651184    |
|     1      | 2020-04-12 00:00:00 |     2.0     |    2.0    |           0.0            |
|     1      | 2020-05-03 00:00:00 |     2.0     |    1.0    |           -0.5           |
|     1      | 2020-05-10 00:00:00 |     2.0     |    1.0    |           -0.5           |
+------------+---------------------+-------------+-----------+--------------------------+
Truncated to displaylimit of 10.

Time since an event

In [6]:
%%sql

with 
    date_vals as 
    (
        select 
            i::date as metric_date
            from 
            generate_series('2020-05-03','2020-05-10','7 day'::interval) i
    ),
    
    last_event as 
    (
        select account_id, metric_date, max(event_time)::date as last_date
            from event e 
            inner join date_vals d 
            on e.event_time::date <= metric_date
            inner join event_type t on t.event_type_id = e.event_type_id
            where t.event_type_name = 'like'
            group by account_id, metric_date
    )
    
select account_id, metric_date, last_date, metric_date - last_date as days_since_last_event
    from last_event
order by days_since_last_event desc

Running query in 'postgresql://postgres:***@localhost/churn'

26955 rows affected.

+------------+-------------+------------+-----------------------+
| account_id | metric_date | last_date  | days_since_last_event |
+------------+-------------+------------+-----------------------+
|    7389    |  2020-05-10 | 2020-01-09 |          122          |
|    3425    |  2020-05-10 | 2020-01-10 |          121          |
|    9349    |  2020-05-10 | 2020-01-12 |          119          |
|    2318    |  2020-05-10 | 2020-01-13 |          118          |
|    1653    |  2020-05-10 | 2020-01-14 |          117          |
|    7389    |  2020-05-03 | 2020-01-09 |          115          |
|    3425    |  2020-05-03 | 2020-01-10 |          114          |
|    9349    |  2020-05-03 | 2020-01-12 |          112          |
|    2318    |  2020-05-03 | 2020-01-13 |          111          |
|    185     |  2020-05-10 | 2020-01-20 |          111          |
+------------+-------------+------------+-----------------------+
Truncated to displaylimit of 10.

In [7]:
%%sql
SELECT
  *
FROM
  metric
WHERE
  metric_name_id = 31

Running query in 'postgresql://postgres:***@localhost/churn'

125736 rows affected.

+------------+---------------------+----------------+--------------+
| account_id |     metric_time     | metric_name_id | metric_value |
+------------+---------------------+----------------+--------------+
|     0      | 2020-03-01 00:00:00 |       31       |     10.0     |
|     0      | 2020-03-08 00:00:00 |       31       |     1.0      |
|     0      | 2020-03-15 00:00:00 |       31       |     8.0      |
|     0      | 2020-03-22 00:00:00 |       31       |     15.0     |
|     0      | 2020-03-29 00:00:00 |       31       |     5.0      |
|     0      | 2020-04-05 00:00:00 |       31       |     1.0      |
|     0      | 2020-04-12 00:00:00 |       31       |     0.0      |
|     0      | 2020-04-19 00:00:00 |       31       |     5.0      |
|     0      | 2020-04-26 00:00:00 |       31       |     12.0     |
|     0      | 2020-05-03 00:00:00 |       31       |     6.0      |
+------------+---------------------+----------------+--------------+
Truncated to displaylimit of 10.

In [8]:
%%sql
SELECT
  *
FROM
  metric_name
ORDER BY
  metric_name_id desc

Running query in 'postgresql://postgres:***@localhost/churn'

21 rows affected.

+----------------+-------------------------------+
| metric_name_id |          metric_name          |
+----------------+-------------------------------+
|       34       |      unfriend_28avg_84obs     |
|       33       |  unfriend_28day_avg_84day_obs |
|       31       |      days_since_newfriend     |
|       30       |    new_friends_pcnt_change    |
|       28       | unfriend_per_newfriend_scaled |
|       27       |        dislike_percent        |
|       26       |         total_opinions        |
|       25       |     unfriend_per_newfriend    |
|       24       |        post_per_message       |
|       23       |         like_per_post         |
+----------------+-------------------------------+
Truncated to displaylimit of 10.

245 92759

243 14967

Scaling a number of events per account

In [9]:
%%sql
    
--son tres meses
    
with date_vals as 
    (
    select i::timestamp as metric_date
    from generate_series('2020-03-01','2020-05-10','7 day'::interval) i
    )
select account_id, metric_date, count(*) as events_per_3_months,
    32::float --days per month
    /
    84::float --days per 3 months
    * count(*) 
    as unfriend_per_month
    from event e 
    inner join date_vals d on e.event_time <= metric_date
    and e.event_time > (metric_date - interval '84 day')
    inner join event_type t on t.event_type_id = e.event_type_id
where event_type_name = 'unfriend'
group by account_id, metric_date
order by metric_date, account_id

--estas agrupando los eventos para ese account id que pasaron en ese intervalo de tipo unfriend

Running query in 'postgresql://postgres:***@localhost/churn'

65333 rows affected.

+------------+---------------------+---------------------+---------------------+
| account_id |     metric_date     | events_per_3_months |  unfriend_per_month |
+------------+---------------------+---------------------+---------------------+
|     3      | 2020-03-01 00:00:00 |          1          | 0.38095238095238093 |
|     8      | 2020-03-01 00:00:00 |          1          | 0.38095238095238093 |
|     13     | 2020-03-01 00:00:00 |          1          | 0.38095238095238093 |
|     16     | 2020-03-01 00:00:00 |          2          |  0.7619047619047619 |
|     17     | 2020-03-01 00:00:00 |          1          | 0.38095238095238093 |
|     20     | 2020-03-01 00:00:00 |          1          | 0.38095238095238093 |
|     21     | 2020-03-01 00:00:00 |          1          | 0.38095238095238093 |
|     24     | 2020-03-01 00:00:00 |          1          | 0.38095238095238093 |
|     25     | 2020-03-01 00:00:00 |          1          | 0.38095238095238093 |
|     26     | 2020-03-01 00:00:00 |          1          | 0.38095238095238093 |
+------------+---------------------+---------------------+---------------------+
Truncated to displaylimit of 10.

In [10]:
%%sql
select * from metric_name order by metric_name_id desc

Running query in 'postgresql://postgres:***@localhost/churn'

21 rows affected.

+----------------+-------------------------------+
| metric_name_id |          metric_name          |
+----------------+-------------------------------+
|       34       |      unfriend_28avg_84obs     |
|       33       |  unfriend_28day_avg_84day_obs |
|       31       |      days_since_newfriend     |
|       30       |    new_friends_pcnt_change    |
|       28       | unfriend_per_newfriend_scaled |
|       27       |        dislike_percent        |
|       26       |         total_opinions        |
|       25       |     unfriend_per_newfriend    |
|       24       |        post_per_message       |
|       23       |         like_per_post         |
+----------------+-------------------------------+
Truncated to displaylimit of 10.

In [11]:
%%sql
SET
	SEARCH_PATH TO SOCIALNET7,
	PUBLIC;

SHOW SEARCH_PATH;

WITH
	CALC_DATE AS (
		SELECT
			'2020-05-06'::TIMESTAMP AS THE_DATE
	)
	--todos los likes del mes pasado 
SELECT
	ACCOUNT_ID,
	COUNT(*) AS N_LIKE_PERMONTH
FROM
	EVENT AS E
	INNER JOIN CALC_DATE AS C ON E.EVENT_TIME <= C.THE_DATE
	AND E.EVENT_TIME > (C.THE_DATE - INTERVAL '28 day')
	INNER JOIN EVENT_TYPE AS T ON E.EVENT_TYPE_ID = T.EVENT_TYPE_ID
WHERE
	T.EVENT_TYPE_NAME = 'like'
GROUP BY
	ACCOUNT_ID
ORDER BY
	N_LIKE_PERMONTH DESC

Running query in 'postgresql://postgres:***@localhost/churn'

1 rows affected.

12408 rows affected.

+------------+-----------------+
| account_id | n_like_permonth |
+------------+-----------------+
|   10749    |       6438      |
|   12478    |       5076      |
|    2101    |       5009      |
|    6944    |       4681      |
|    6036    |       4198      |
|    7685    |       4018      |
|    3305    |       3619      |
|    5249    |       3378      |
|   12224    |       3377      |
|    3941    |       3151      |
+------------+-----------------+
Truncated to displaylimit of 10.

In [12]:
%%sql
select * from event_type

Running query in 'postgresql://postgres:***@localhost/churn'

8 rows affected.

+---------------+-----------------+
| event_type_id | event_type_name |
+---------------+-----------------+
|       0       |       post      |
|       1       |    newfriend    |
|       2       |       like      |
|       3       |      adview     |
|       4       |     dislike     |
|       5       |     unfriend    |
|       6       |     message     |
|       7       |      reply      |
+---------------+-----------------+

In [13]:
%%sql

--el evento unfried paso antes o igual a la metrica de account tenure
--el tenia un account tenure de 26

--esta calculando unfriend per month
--los eventos por metricas 
select m.account_id, metric_time, 
    metric_value as tenure_metric,
    count(*) as count_unscaled,
    28 / least(84, metric_value) as scaling,
    28 / least(84, metric_value) * count(*) as unfriend_per_month
    from event e 
    inner join metric m on e.account_id = m.account_id 
    and event_time <= metric_time
    and event_time > metric_time - interval '84 days'
inner join event_type t on t.event_type_id = e.event_type_id
inner join metric_name n on n.metric_name_id = m.metric_name_id
where event_type_name = 'unfriend' 
    and metric_name = 'account_tenure' 
    and metric_value >= 14
    and 28 / least(84, metric_value) <= 2
group by m.account_id, metric_time, metric_value
order by count_unscaled desc

Running query in 'postgresql://postgres:***@localhost/churn'

70319 rows affected.

+------------+---------------------+---------------+----------------+--------------------+--------------------+
| account_id |     metric_time     | tenure_metric | count_unscaled |      scaling       | unfriend_per_month |
+------------+---------------------+---------------+----------------+--------------------+--------------------+
|    7197    | 2020-05-03 00:00:00 |     116.0     |       7        | 0.3333333333333333 | 2.333333333333333  |
|    7197    | 2020-05-10 00:00:00 |     123.0     |       7        | 0.3333333333333333 | 2.333333333333333  |
|    9215    | 2020-04-19 00:00:00 |      87.0     |       6        | 0.3333333333333333 |        2.0         |
|    9215    | 2020-04-12 00:00:00 |      80.0     |       6        |        0.35        | 2.0999999999999996 |
|    9215    | 2020-04-05 00:00:00 |      73.0     |       6        | 0.3835616438356164 | 2.3013698630136985 |
|    8143    | 2020-04-26 00:00:00 |      97.0     |       6        | 0.3333333333333333 |        2.0         |
|    9717    | 2020-05-03 00:00:00 |     100.0     |       6        | 0.3333333333333333 |        2.0         |
|    8143    | 2020-05-03 00:00:00 |     104.0     |       6        | 0.3333333333333333 |        2.0         |
|    9717    | 2020-05-10 00:00:00 |     107.0     |       6        | 0.3333333333333333 |        2.0         |
|    9215    | 2020-04-26 00:00:00 |      94.0     |       6        | 0.3333333333333333 |        2.0         |
+------------+---------------------+---------------+----------------+--------------------+--------------------+
Truncated to displaylimit of 10.

70319

In [20]:
%%sql
select * from metric_name order by metric_name_id desc

Running query in 'postgresql://postgres:***@localhost/churn'

21 rows affected.

+----------------+-------------------------------+
| metric_name_id |          metric_name          |
+----------------+-------------------------------+
|       34       |      unfriend_28avg_84obs     |
|       33       |  unfriend_28day_avg_84day_obs |
|       31       |      days_since_newfriend     |
|       30       |    new_friends_pcnt_change    |
|       28       | unfriend_per_newfriend_scaled |
|       27       |        dislike_percent        |
|       26       |         total_opinions        |
|       25       |     unfriend_per_newfriend    |
|       24       |        post_per_message       |
|       23       |         like_per_post         |
+----------------+-------------------------------+
Truncated to displaylimit of 10.

meta

In [65]:
%%sql
    
set search_path = 'socialnet7'; with observation_params as
(
    select  interval '7 day' as metric_period,
    '2020-03-01'::timestamp as obs_start,
    '2020-05-10'::timestamp as obs_end
)
select m.account_id, o.observation_date, is_churn,
sum(case when metric_name_id=0 then metric_value else 0 end) as like_per_month,
sum(case when metric_name_id=1 then metric_value else 0 end) as newfriend_per_month,
sum(case when metric_name_id=2 then metric_value else 0 end) as post_per_month,
sum(case when metric_name_id=3 then metric_value else 0 end) as adview_per_month,
sum(case when metric_name_id=4 then metric_value else 0 end) as dislike_per_month,
    
sum(case when metric_name_id=34 then metric_value else 0 end) as unfriend_per_month,
    
sum(case when metric_name_id=6 then metric_value else 0 end) as message_per_month,
sum(case when metric_name_id=7 then metric_value else 0 end) as reply_per_month,
    
--sum(case when metric_name_id=8 then metric_value else 0 end) as account_tenure,
    
sum(case when metric_name_id=21 then metric_value else 0 end) as adview_per_post,
    
sum(case when metric_name_id=22 then metric_value else 0 end) as reply_per_message,
    
sum(case when metric_name_id=23 then metric_value else 0 end) as like_per_post,
    
sum(case when metric_name_id=24 then metric_value else 0 end) as post_per_message,

sum(case when metric_name_id=28 then metric_value else 0 end) as unfriend_per_newfriend,

sum(case when metric_name_id=27 then metric_value else 0 end) as dislike_pcnt,

--sum(case when metric_name_id=28 then metric_value else 0 end) as unfriend_per_newfriend_scaled,

sum(case when metric_name_id=30 then metric_value else 0 end) as newfriend_pcnt_chng,
    
sum(case when metric_name_id=31 then metric_value else 0 end) as days_since_newfriend

--sum(case when metric_name_id=33 then metric_value else 0 end) as unfriend_28day_avg_84day_obs

--sum(case when metric_name_id=34 then metric_value else 0 end) as unfriend_28day_avg_84day_obs_scaled
    
from metric m inner join observation_params
on metric_time between obs_start and obs_end
inner join observation o on m.account_id = o.account_id
    and m.metric_time > (o.observation_date - metric_period)::timestamp
    and m.metric_time <= o.observation_date::timestamp
group by m.account_id, metric_time, observation_date, is_churn
order by observation_date,m.account_id

Running query in 'postgresql://postgres:***@localhost/churn'

25806 rows affected.

,account_id,observation_date,is_churn,like_per_month,newfriend_per_month,post_per_month,adview_per_month,dislike_per_month,unfriend_per_month,message_per_month,reply_per_month,adview_per_post,reply_per_message,like_per_post,post_per_message,unfriend_per_newfriend,dislike_pcnt,newfriend_pcnt_chng,days_since_newfriend
0,27,2020-03-01,False,28.0,5.0,14.0,33.0,2.0,0.509091,1.0,0.0,2.357143,0.000000,2.000000,14.000000,0.101818,0.066667,4.000000,3.0
1,51,2020-03-01,False,26.0,5.0,4.0,19.0,4.0,1.018182,42.0,28.0,4.750000,0.666667,6.500000,0.095238,0.203636,0.133333,-0.166667,1.0
2,95,2020-03-01,False,74.0,5.0,64.0,17.0,20.0,0.000000,12.0,6.0,0.265625,0.500000,1.156250,5.333334,0.000000,0.212766,0.250000,1.0
3,123,2020-03-01,False,28.0,6.0,13.0,4.0,25.0,0.000000,11.0,1.0,0.307692,0.090909,2.153846,1.181818,0.000000,0.471698,1.000000,2.0
4,189,2020-03-01,True,3.0,1.0,8.0,16.0,2.0,0.000000,0.0,0.0,2.000000,0.000000,0.375000,0.000000,0.000000,0.400000,0.000000,15.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25801,13132,2020-05-10,False,19.0,0.0,20.0,2.0,3.0,0.000000,27.0,6.0,0.100000,0.222222,0.950000,0.740741,0.000000,0.136364,0.000000,0.0
25802,13141,2020-05-10,False,3.0,1.0,6.0,9.0,1.0,0.000000,13.0,5.0,1.500000,0.384615,0.500000,0.461538,0.000000,0.250000,0.000000,18.0
25803,13155,2020-05-10,False,2.0,0.0,1.0,1.0,1.0,0.000000,27.0,17.0,1.000000,0.629630,2.000000,0.037037,0.000000,0.333333,0.000000,0.0
25804,13171,2020-05-10,False,15.0,6.0,44.0,16.0,1.0,0.000000,26.0,6.0,0.363636,0.230769,0.340909,1.692308,0.000000,0.062500,0.000000,6.0
25805,13248,2020-05-10,False,439.0,50.0,276.0,664.0,44.0,1.120000,448.0,50.0,2.405797,0.111607,1.590580,0.616071,0.022400,0.091097,0.000000,0.0

In [68]:
%%sql

delete from metric where metric_name_id = 28

Running query in 'postgresql://postgres:***@localhost/churn'

112557 rows affected.

Empty DataFrame
Columns: []
Index: []

In [70]:
%%sql
select * from metric where metric_name_id = 28

Running query in 'postgresql://postgres:***@localhost/churn'

Empty DataFrame
Columns: [account_id, metric_time, metric_name_id, metric_value]
Index: []

In [71]:
%%sql
    
INSERT into metric_name values (28,concat('unfriend_per_newfriend_scaled'))
ON CONFLICT DO NOTHING;

with num_metric as (
	select account_id, metric_time, metric_value as num_value
	from metric m inner join metric_name n on n.metric_name_id=m.metric_name_id
	and n.metric_name = 'unfriend_28avg_84obs_scaled'
	and metric_time between '2020-03-01' and '2020-05-10'
), den_metric as (
	select account_id, metric_time, metric_value as den_value
	from metric m inner join metric_name n on n.metric_name_id=m.metric_name_id
	and n.metric_name = 'newfriend_per_month'
	and metric_time between '2020-03-01' and '2020-05-10'
)
insert into metric (account_id,metric_time,metric_name_id,metric_value)
select d.account_id, d.metric_time, 28,
	case when den_value > 0
	    then coalesce(num_value,0.0)/den_value
	    else 0
    end as metric_value
from den_metric d  left outer join num_metric n
	on n.account_id=d.account_id
	and n.metric_time=d.metric_time

Running query in 'postgresql://postgres:***@localhost/churn'

112557 rows affected.

Empty DataFrame
Columns: []
Index: []

In [72]:
%%sql
select * from metric where metric_name_id = 28

Running query in 'postgresql://postgres:***@localhost/churn'

112557 rows affected.

        account_id metric_time  metric_name_id  metric_value
0                0  2020-03-01              28           0.0
1                0  2020-03-08              28           0.0
2                0  2020-03-15              28           0.0
3                0  2020-03-22              28           0.0
4                0  2020-03-29              28           0.0
...            ...         ...             ...           ...
112552       14610  2020-05-10              28           0.0
112553       14612  2020-05-10              28           0.0
112554       14614  2020-05-10              28           0.0
112555       14624  2020-05-10              28           0.0
112556       14626  2020-05-10              28           0.0

[112557 rows x 4 columns]

In [36]:
import pandas as pd
from sqlalchemy import create_engine

DB_USER = 'postgres'
DB_PASSWORD = 'postgres'
DB_HOST = 'localhost'
DB_PORT = '5432'
DB_NAME = 'churn'

database_url = f"postgresql+psycopg2://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}"
database_url

'postgresql+psycopg2://postgres:postgres@localhost:5432/churn'

In [44]:
sql_query = """set search_path = 'socialnet7'; with observation_params as
(
    select  interval '7 day' as metric_period,
    '2020-03-01'::timestamp as obs_start,
    '2020-05-10'::timestamp as obs_end
)
select m.account_id, o.observation_date, is_churn,
sum(case when metric_name_id=0 then metric_value else 0 end) as like_per_month,
sum(case when metric_name_id=1 then metric_value else 0 end) as newfriend_per_month,
sum(case when metric_name_id=2 then metric_value else 0 end) as post_per_month,
sum(case when metric_name_id=3 then metric_value else 0 end) as adview_per_month,
sum(case when metric_name_id=4 then metric_value else 0 end) as dislike_per_month,
    
sum(case when metric_name_id=34 then metric_value else 0 end) as unfriend_per_month,
    
sum(case when metric_name_id=6 then metric_value else 0 end) as message_per_month,
sum(case when metric_name_id=7 then metric_value else 0 end) as reply_per_month,
    
--sum(case when metric_name_id=8 then metric_value else 0 end) as account_tenure,
    
sum(case when metric_name_id=21 then metric_value else 0 end) as adview_per_post,
    
sum(case when metric_name_id=22 then metric_value else 0 end) as reply_per_message,
    
sum(case when metric_name_id=23 then metric_value else 0 end) as like_per_post,
    
sum(case when metric_name_id=24 then metric_value else 0 end) as post_per_message,

sum(case when metric_name_id=28 then metric_value else 0 end) as unfriend_per_newfriend,

sum(case when metric_name_id=27 then metric_value else 0 end) as dislike_pcnt,

--sum(case when metric_name_id=28 then metric_value else 0 end) as unfriend_per_newfriend_scaled,

sum(case when metric_name_id=30 then metric_value else 0 end) as newfriend_pcnt_chng,
    
sum(case when metric_name_id=31 then metric_value else 0 end) as days_since_newfriend

--sum(case when metric_name_id=33 then metric_value else 0 end) as unfriend_28day_avg_84day_obs

--sum(case when metric_name_id=34 then metric_value else 0 end) as unfriend_28day_avg_84day_obs_scaled
from metric m inner join observation_params
on metric_time between obs_start and obs_end
inner join observation o on m.account_id = o.account_id
    and m.metric_time > (o.observation_date - metric_period)::timestamp
    and m.metric_time <= o.observation_date::timestamp
group by m.account_id, metric_time, observation_date, is_churn
order by observation_date,m.account_id"""

sql_query

"set search_path = 'socialnet7'; with observation_params as\n(\n    select  interval '7 day' as metric_period,\n    '2020-03-01'::timestamp as obs_start,\n    '2020-05-10'::timestamp as obs_end\n)\nselect m.account_id, o.observation_date, is_churn,\nsum(case when metric_name_id=0 then metric_value else 0 end) as like_per_month,\nsum(case when metric_name_id=1 then metric_value else 0 end) as newfriend_per_month,\nsum(case when metric_name_id=2 then metric_value else 0 end) as post_per_month,\nsum(case when metric_name_id=3 then metric_value else 0 end) as adview_per_month,\nsum(case when metric_name_id=4 then metric_value else 0 end) as dislike_per_month,\n\nsum(case when metric_name_id=34 then metric_value else 0 end) as unfriend_per_month,\n\nsum(case when metric_name_id=6 then metric_value else 0 end) as message_per_month,\nsum(case when metric_name_id=7 then metric_value else 0 end) as reply_per_month,\n\n--sum(case when metric_name_id=8 then metric_value else 0 end) as account_tenure,\n\nsum(case when metric_name_id=21 then metric_value else 0 end) as adview_per_post,\n\nsum(case when metric_name_id=22 then metric_value else 0 end) as reply_per_message,\n\nsum(case when metric_name_id=23 then metric_value else 0 end) as like_per_post,\n\nsum(case when metric_name_id=24 then metric_value else 0 end) as post_per_message,\n\nsum(case when metric_name_id=28 then metric_value else 0 end) as unfriend_per_newfriend,\n\nsum(case when metric_name_id=27 then metric_value else 0 end) as dislike_pcnt,\n\n--sum(case when metric_name_id=28 then metric_value else 0 end) as unfriend_per_newfriend_scaled,\n\nsum(case when metric_name_id=30 then metric_value else 0 end) as newfriend_pcnt_chng,\n\nsum(case when metric_name_id=31 then metric_value else 0 end) as days_since_newfriend\n\n--sum(case when metric_name_id=33 then metric_value else 0 end) as unfriend_28day_avg_84day_obs\n\n--sum(case when metric_name_id=34 then metric_value else 0 end) as unfriend_28day_avg_84day_obs_scaled\nfrom metric m inner join observation_params\non metric_time between obs_start and obs_end\ninner join observation o on m.account_id = o.account_id\n    and m.metric_time > (o.observation_date - metric_period)::timestamp\n    and m.metric_time <= o.observation_date::timestamp\ngroup by m.account_id, metric_time, observation_date, is_churn\norder by observation_date,m.account_id"

In [51]:
engine = create_engine(database_url)
connection = engine.connect()
connection

In [64]:
df = pd.read_sql(sql_query,connection, index_col=['account_id','observation_date'])
df.to_csv('original.csv',header=True)